dist: xenial
addons:
  postgresql: '9.6'
language: java
jdk:
- openjdk8
services:
- mysql
- postgresql
- docker
git:
  depth: false
install: "./travis/installViaTravis.sh"
before_script:
- cat "$TRAVIS_BUILD_DIR/travis/config/mysql/my.cnf" | sudo tee -a /etc/mysql/my.cnf
- sudo service mysql restart
- mysql -u root -e 'create database genie;'
- psql  -U postgres -c 'create database genie;'
script: "./travis/buildViaTravis.sh"
before_cache:
- rm -f  "${HOME}/.gradle/caches/modules-2/modules-2.lock"
- rm -fr "${HOME}/.gradle/caches/*/plugin-resolution/"
- rm -f  "${HOME}/.gradle/caches/*/fileHashes/fileHashes.bin"
- rm -f  "${HOME}/.gradle/caches/*/fileHashes/fileHashes.lock"
cache:
  directories:
  - "${HOME}/.gradle/caches/"
  - "${HOME}/.gradle/wrapper/"
  - genie-ui/node_modules/
  - genie-ui/.gradle/nodejs
  - genie-ui/.gradle/npm
  timeout: 1000
env:
  global:
  - secure: a5QmXCWR7wwEf/poWSj3PDAb6VICKqTTw3qbNjQwSvCzaCYtZZmxLbruQQlKOyR6W4j2VMrp2Ip5xrBjlCrOTvkFymPY3L+EwbPxsXbO4uhzs43BNFLhDon/Duv3TRhnedkqP0s8hN1ylxCbcID0UUPXQGrhnu8mb5QlDUx2mr8=
  - secure: GD9O3tWgiQ5fczS931uFjRtHZk6IDPam3jKyJPc/5lkRdeJo7ZQhqIjffgaA8mAcLumbORkxG1Q0C/UC7DPxa7W23JCikwlT58d/jNK/dU5ZR7bklwiXkBBBajmRoP3fJGGNV1Zkf095FbkepeSKi7o66xtCornQgAsNJVPKXJY=
  - secure: Dib1l7wKxkpx4Bt2fC6kv0O4oB7dLfY4zmeQE28yXEC/FKY32p21JcxjisVfdBZzSmHnDi2Oc3oQzpFHa0tZyRZ/SvrKbmydCE+MLrIHXethM1/UzlENUdA2wY1FPRdqp3fEmClhJ94a1CDjP4k6MgTc9BIHQaR1RG3Ze6ll1Hk=
  - secure: FRN5YVCoJOKnfNsi0WJtGZFsaoPbtz/YhQq0X0UwrC99waegSVBsznAmlD41l8bJQ07IsT3wAu1TfT6UDNlK2VulAIuOiAETHCCyeRfg2wMbeU4jPR6ZvGd9yMMjDzrLoKmxbCtue0mBaLjWuuFfgbNHkOys36rsAGprLOhQLd8=
  - secure: X1zVhsEPD+9udVNymSMwRjKXfSKK3mrs1ZXXMuLnl4JiNEc3nSEt0WF/4UeCUd6ZsUSHFpDGUd8jYMPv5nnYVyRSsApeaz2nuII1Y+VR8kUmgeEOwV0nU4cUMf+nb9FXL1FAZl4BSFMC+gvc4dXAZuyoyrACeBG11tEy9wqFq7g=
  - secure: VCaLy5Pv5UkzT0ZNHEomALUbdAuK+WU1K3H/Rujo2ylWMFUMoEUBvBO1fVcWBqVMJThtHA1zJzUl6xKcndZp3vG0UCNycrW4uCK062BIB93JytqV+O9cvdzPy0lzhxBPq0TTv4zyP3IP1nZ5x0dqDJZxRK2VbMvaWjMNiZFKnxY=
  - secure: ZfwgI/1ICEcoaWg3pD0O4KVcHxCB05dow8bq61XVDUsjxUyT45EFS4/Xv+IdNoreJVYmyLtcgl5mybsfPjdGV+oDdQ5A+6RFfkOM7lNxPiUFGV6fB69d7fOVQKoE+f2fcgkwf/fzRl39T3Wx4cyy8nc3aaSAoWblTncDusrbr0s=
  - secure: Z7l4O6gvS1FFhWydARZ8ZY+V4qNfsup8nAO0mzgsd/p8MLJ99710cs+8y8k/sqnt3sYpKj8+V5dX9s5jX6w7s5mGCyShyD3soCVR1W6Fu1A53amy1XcO9NjRgLmzC9Wf/Kwnjgyf/KBjtgYjx2tkKPz0EpVNWDgUe1s5nLK+/Vo=
  - secure: F3IO3LiiABMyzsmF9GhHbJ3rPtJXW3I8xSARu12ThKmncrNQaeWihHIZ69vc8DgGRH9S7qz4AD95lNLNvN2Ll9sHRh5aTYrX/Phze62BFuUeBY2PdyWcaSPxIIErjH9WcSiMRbfk4CzF3WKg9cWcPnxx5P4sfCc0ulssIWeD4Yo=
notifications:
  slack:
    secure: H5nS+GX6TYTU27ur6YFG5OgrQeUbzXLok5ub6+xcmyYEeVPpnQ1Gg/wKqTAGsP9j6tAkqPpxgYT9i9Do6eyTEplK6bTvQVyhilsEDtxGJbUO8XOE9TSo6jAe/lD3EB5l46gxFID+Hg9IkPii4LwEabP7PVehrB1JfNZ6QDgSRRM=
