name: ci
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup jdk 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/cache@v1
        id: gradle-cache
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle/dependency-locks/*.lockfile') }}
          restore-keys: |
            - ${{ runner.os }}-gradle-
      - uses: actions/cache@v1
        id: gradle-wrapper-cache
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradlewrapper-${{ hashFiles('gradle/wrapper/*') }}
          restore-keys: |
            - ${{ runner.os }}-gradlewrapper-
      - uses: actions/cache@v1
        id: genie-ui-node-modules
        with:
          path: genie-ui/node_modules/
          key: ${{ runner.os }}-genie-ui-node-modules-${{ hashFiles('genie-ui/node_modules/*') }}
          restore-keys: |
            - ${{ runner.os }}-genie-ui-node-modules-
      - uses: actions/cache@v1
        id: genie-ui-gradle-nodejs
        with:
          path: genie-ui/.gradle/nodejs
          key: ${{ runner.os }}-genie-ui-gradle-nodejs-${{ hashFiles('genie-ui/.gradle/nodejs/*') }}
          restore-keys: |
            - ${{ runner.os }}-genie-ui-gradle-nodejs-
      - uses: actions/cache@v1
        id: genie-ui-gradle-npm
        with:
          path: genie-ui/.gradle/npm
          key: ${{ runner.os }}-genie-ui-gradle-npm-${{ hashFiles('genie-ui/.gradle/npm/*') }}
          restore-keys: |
            - ${{ runner.os }}-genie-ui-gradle-npm-

      - name: Build with Gradle
        run: |
          ./gradlew --stacktrace build codeCoverageReport coveralls
          INTEGRATION_TEST_DB=mysql ./gradlew --stacktrace genie-web:integrationTest
          INTEGRATION_TEST_DB=postgresql ./gradlew --stacktrace genie-web:integrationTest
          ./gradlew --stacktrace javadoc asciidoc dockerBuildAllImages
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
